name = "Blocky Getaway"
author = "Kaioru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "743293b69b934e10bd5137e944d2ef5b4a3fa0e8d7d538b487f7a8147154b208"

[versions]
minecraft = "1.19.2"
quilt = "0.18.5"
