name = "Blocky Getaway"
author = "Kaioru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0226d0c4e33e08fa937e7342da498e3e71ccb328378dbad94abfb45d318a8c7f"

[versions]
minecraft = "1.19.2"
quilt = "0.18.5"
