name = "Blocky Getaway"
author = "Kaioru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "394cd829640dfbcea0f60b44ff14d8a297090f411333f1773a026ee6a27c648c"

[versions]
minecraft = "1.19.2"
quilt = "0.18.5"
