name = "Blocky Getaway"
author = "Kaioru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45a5b9b4b72b0e19fee9ccc7dfa63beced41d54191e3af6ade22402bc2e2133e"

[versions]
minecraft = "1.19.2"
quilt = "0.18.5"
