name = "Blocky Getaway"
author = "Kaioru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d50420562125f7df86aea089e82424bda1bce27ce8145c269692081519fe3ba2"

[versions]
minecraft = "1.19.2"
quilt = "0.18.5"
