name = "Blocky Getaway"
author = "Kaioru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98827966cf0d62d8c701fb91f474018ab54bd1631db896660aabdb41f2433687"

[versions]
minecraft = "1.19.2"
quilt = "0.18.5"
