name = "Blocky Getaway"
author = "Kaioru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7749da593ffa4c4c42173c9dee40d43e7f6294f34752e198903f14d257da6caa"

[versions]
minecraft = "1.19.2"
quilt = "0.18.5"
