name = "Blocky Getaway"
author = "Kaioru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fc4ee19b36c05beafbb28cd5c93a8de1d6e1c81b54e2ddda31e70551297ec86"

[versions]
minecraft = "1.19.2"
quilt = "0.18.5"
