name = "Blocky Getaway"
author = "Kaioru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c0af0b664fdc56901a0e2c525fd76f64fa73d0a5d0c0271ecef0a503f9edd88"

[versions]
minecraft = "1.19.2"
quilt = "0.18.5"
