name = "Blocky Getaway"
author = "Kaioru"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "171023e0ee5d87855ba3512d7999c4ff0bc36113e57d9678eb08d26f35e0fa62"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.2"]
