name = "Blocky Getaway"
author = "Kaioru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "398b46daeec28d1867db638f020e2c7009fe38f27f128ec99a3ea96e2a9ba3cd"

[versions]
minecraft = "1.19.2"
quilt = "0.18.5"
