name = "Blocky Getaway"
author = "Kaioru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "158e5ec68df93965b3378f2b1535052b8289bfda6a179ee9d4650a5682d9bd03"

[versions]
minecraft = "1.19.2"
quilt = "0.18.5"
